config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "pages/about" => "pages#about", as: :about
  get "pages/home" => "pages#home", as: :home
  resources :signups
  get "signups/new" => "signups#new", as: :contact
  post "signups/new" => "signups#create"
  get "pages/thanks" => "pages#thanks"

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup = Signup.new
  end
  def create
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to '/pages/thanks'
    else
      render 'new'
    end
  end
  private
  def signup_params
    params.require(:signup).permit(:firstname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for?(:head) %>
  <%= content_for(:head) %>
  <% else %>
  <title>Welcome to Stories</title>
  <% end %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Quicksand:400,300,700' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <menu>
    <ul class="menu">
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      </ul>
    <img id="button-close" src="http://s3.amazonaws.com/codecademy-content/projects/z2d/stories/close-black.svg" alt="close">
   </menu>
     <img id="button-menu" src="http://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-white.svg" alt="menu-button">
<%= yield %>
  
<footer>
  <p>Elturista project &copy 2015</p>
</footer>  
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :head do %>
<title>About Stories</title>
<% end %>

<main>
  <div class="about">
    <h1>Relive your favourite memories</h1>
  </div>
  <div class="about-secondary">
    <h1>No more sorting through photos</h1>
    <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
    <%= link_to "Signup", contact_path, :class=>"btn btn-default learn" %>
  </div>
</main>

app/views/pages/home.html.erb
<main>
  <div class="home-create">
    <h1>Create and share Stories</h1>
    <%= link_to "Learn more", about_path, :class=>"btn btn-default learn" %>
  </div>
  <div class="support">
      <h1>Relieve and share your adventures</h1>
      <p>Stories automatically creates a digital journal filled with only your best photos</p>
  </div>
  <div class="secondary">
  </div>
  <div class="discover">
    <h1>Discover Stories</h1>
    <%= link_to "Learn more", about_path, :class=>"btn btn-default learn" %>
  </div>
</main>

app/views/pages/thanks.html.erb
<% content_for :head do %>
<title>Thank you for signing up to Stories</title>
<% end %>

<main>
  <div class="signups">
    <div class="signups-text">
    <h1>Thanks. We will be in touch.</h1>
    </div>
  </div>
</main>

app/views/signups/new.html.erb
<% content_for :head do %>
<title> Sign up to Stories</title>
<% end %>

<main>
  <div class="signups">
    <div class="signups-text">
    <h1>Get the latest updates from Stories</h1>
    <div class="form">
    <form class="signupform" method="post">
      <%= form_for(@signup) do |f|  %>  
      <label>First name</label>
      <%= f.text_field :firstname %>
      <label>E-mail</label>
      <%= f.email_field :email %>
      <%= f.submit "Join", :class=>"btn btn-default join" %> 
       <% end %>
    </form>
    </div>
    </div>
  </div>
</main>